Syntax 3

SectionUseCase."Headphones" {
	File "/Qualcomm/qcm2290/Headphones.conf"
	Comment "Headphones"
}

SectionUseCase."LineOut" {
	File "/Qualcomm/qcm2290/Lineout.conf"
	Comment "Line out"
}

SectionUseCase."Earphones" {
	File "/Qualcomm/qcm2290/Earphones.conf"
	Comment "Earphones"
}

SectionUseCase."HDMI" {
	File "/Qualcomm/qcm2290/HDMI.conf"
	Comment "HDMI"
}