# Use case configuration for Arduino-Imola board.
# Author: Srinivas Kandagatla <srinivas.kandagatla@oss.qualcomm.com>
# Author: Riccardo Mereu <r.mereu@arduino.cc>

SectionVerb {

	EnableSequence [
		cset "name='RX_CODEC_DMA_RX_0 Audio Mixer MultiMedia1' 1"
		cset "name='MultiMedia3 Mixer TX_CODEC_DMA_TX_3' 1"
	]

	DisableSequence [
		cset "name='RX_CODEC_DMA_RX_0 Audio Mixer MultiMedia1' 0"
		cset "name='MultiMedia3 Mixer TX_CODEC_DMA_TX_3' 0"
	]

	Value {
		TQ "HiFi"
	}
}

SectionDevice."Headphones" {
	Comment "Headphones playback"

	Include.wcdhpe.File "/codecs/pm4125/HeadphoneEnableSeq.conf"
	Include.wcdhpd.File "/codecs/pm4125/HeadphoneDisableSeq.conf"
	Include.rxmhpe.File "/codecs/qcom-lpass/rx-macro/HeadphoneEnableSeq.conf"
	Include.rxmhpd.File "/codecs/qcom-lpass/rx-macro/HeadphoneDisableSeq.conf"

	Value {
		PlaybackPriority 200
		PlaybackPCM "hw:${CardId},0"
		PlaybackMixer "hw:${CardId}"
		PlaybackMixerElem "RX_RX0 Digital"
		PlaybackMixerElem "RX_RX1 Digital"
		#JackControl "Headphone Jack"
	}
}

SectionDevice."Headset" {
	Comment "Headset microphone"

	Include.wcdmice.File "/codecs/pm4125/HeadphoneMicEnableSeq.conf"
	Include.wcdmicd.File "/codecs/pm4125/HeadphoneMicDisableSeq.conf"
	Include.txmhpe.File "/codecs/qcom-lpass/tx-macro/SoundwireMic1EnableSeq.conf"
	Include.txmhpd.File "/codecs/qcom-lpass/tx-macro/SoundwireMicDisableSeq.conf"

	EnableSequence [
		cset "name='ADC2 Volume' 0"
		cset "name='TX_DEC0 Volume' 80"
	]

	DisableSequence [
		cset "name='TX_DEC0 Volume' 0"
	]

	Value {
		CapturePriority 200
		CapturePCM "hw:${CardId},2"
		CaptureMixer "hw:${CardId}"
		CaptureMixerElem "TX_DEC0"
		CaptureVolume "TX_DEC0 Volume"
		#JackControl "Mic Jack"
	}
}
